#!/bin/sh

echo "it will run the client default, if you want to run server, please append 'server' arg to the docker run."
echo "usage: docker run theanony/frp:0.44.0"
echo "       docker run theanony/frp:0.44.0 server"
echo "       docker run -v ./frpc.ini:/frp/frpc.ini:ro theanony/frp:0.44.0"
echo "       docker run -v ./frps.ini:/frp/frps.ini:ro theanony/frp:0.44.0 server"
echo ""

execute=frpc
if [ -n "$1" ]; then execute=frps; fi

./$execute -c ${execute}.ini
